import localFont from "next/font/local";
import Providers from "../providers/providers";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.ttf",
  variable: "--font-pretendard-variable",
});

const rokaf = localFont({
  src: "../fonts/ROKAFSansMedium.ttf",
  variable: "--font-rokaf-sans",
});

export const metadata = {
  title: "판다마켓 ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${rokaf.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
