import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.ttf",
  variable: "--font-pretendard-variable",
});

const rokaf = localFont({
  src: "../fonts/ROKAFSansMedium.ttf",
  variable: "--font-rokaf-sans",
});

export const metadata = {
  title: "판다마켓 ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${rokaf.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main className="flex-1 mt-[64px] bg-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
